### ISSUE TITLE
question: arm cortex a9

### ISSUE THREAD

**Issue by Arnold1** [payne92/bare-metal-arm#13]
Hello,

did you also test it for arm cortex a9? will i be able to use the same compiler? arm-none-eabi-gcc

Thanks,
A

**Comment by payne92** [comment]
Unfortunately, no.  Right now, this basic example has only been tested on the original Freescale freedom board:  http://www.freescale.com/webapp/sps/site/prod_summary.jsp?code=FRDM-KL25Z

Others have reported to me (privately) success in getting it to run on other boards relatively easily, by updating the linker map and compiler options.  Expanding board and processor support has been on my list for a while, but I haven't had time.  For example, see:  #7 and #10
