### ISSUE TITLE
sys/types.h no such file or directory.. How to add gcc compiler in KEIL IDE.

### ISSUE THREAD

**Issue by sarwadenj** [payne92/bare-metal-arm#14]
Hi,

While programming STM32F103C8 board I'm getting following error when i tried to use ARMCC and ARMCLANG, ARM compiler

\platform\syscalls.c(13): error: #5: cannot open source input file "sys/types.h": No such file or directory

As sys/types.h, types.h, sys/stat.h, unistd.h are Newlib implementation then I tried using GCC Compiler(GNU) for ARM Project compiler

--- Error: failed to execute 'arm-none-eabi-gcc'

![error](https://user-images.githubusercontent.com/20920439/29116500-9c0589ce-7d18-11e7-9bbe-41eea6e67e1c.png)

**Comment by payne92** [comment]
This project doesn't use the KEIL IDE and isn't for the STM32F103C8 processor or any STM board.   

If you're having an issue with the code **in this repository**, I'm glad to try and help.
